### ISSUE TITLE
undefined has left the server!

### ISSUE THREAD

**Issue by baburaomastani** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#13]
i dont know why 
when i quit my my world (mean server) 
after that is start spamming me undefined has left the server! in discord chat
pls help

**Comment by TheShadowEevee** [comment]
Just to confirm a few things:
 - What version of BDSX are you running?
 - Is this a new problem/have you used the plugin without this issue before?
- Does this happen again if you restart your server first?

I'll start investigating this now, in the meantime if this is a repeatable issue I recommend disabling player join/leaves in the config until this issue is resolved.

**Comment by baburaomastani** [comment]
dude i guess u fixed it

thanks dude

**Comment by TheShadowEevee** [comment]
Good to hear! If anything happens in the future please be sure to open a new issue so I can help out!

**Comment by baburaomastani** [comment]
nice dude
