### ISSUE TITLE
Update discord chatter to 1.19 bdsx?

### ISSUE THREAD

**Issue by Xiang910** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#15]
when I use it it crashed in 1.19 bdsx :(

**Comment by TheShadowEevee** [comment]
I'm sorry this is such a late reply, this issue was fixed a few months ago in Commit bfa929f. The issue is that this fix was marked temporarily as a pre-release as it wasn't an elegant fix. It has been long enough now though that rolling it into a normal release is a good move. Please grab the plugin directly from [source](https://github.com/TheShadowEevee/BDSX-Discord-Chatter-Plugin/archive/refs/heads/main.zip) or download [compatibility release 1.1.2](https://github.com/TheShadowEevee/BDSX-Discord-Chatter-Plugin/releases/tag/1.1.2), both of which have the fix. Thank you for using the plugin and I apologize again for the inconvenience and the wait!
