### ISSUE TITLE
Player join/leave messages doesnt show up

### ISSUE THREAD

**Issue by bibihool** [TheShadowEevee/BDSX-Discord-Chatter-Plugin#8]
at newset version 1.18.0.02 didint show player connect or disconnect messages on discord

**Comment by TheShadowEevee** [comment]
Hmm... It's possible 1.18 changed the join/leave message in someway, or changed the way join/leave events are broadcast. I'll spin up a 1.18 server later today and try to find the issue.

**Comment by TheShadowEevee** [comment]
I'm working on solving this, for now on the latest commit player joins work but player leaves don't say anything in Discord.

The underlying issue is that BDS no longer seems to put Join/Leave messages in the ServerLog event packets and so that isn't a viable way to listen for them anymore. There is an event specifically for Player Joins that the plugin now uses, but I have not found a suitable way to track and report disconnects.

**Comment by TheShadowEevee** [comment]
This should be fixed in Hotfix v1.0.5.

Please download the patch [here](https://github.com/TheShadowEevee/BDSX-Discord-Chatter-Plugin/releases/tag/1.0.5).
